branch-defaults:
  master:
    environment: wign-prod
    group_suffix: null
global:
  application_name: wign
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker 17.03.1-ce
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
